tmp0 = $00
tmp1 = $01
tmp2 = $02
tmp3 = $03
tmp4 = $04
tmp5 = $05
tmp6 = $06
tmp7 = $07
tmp8 = $08
tmp9 = $09
tmpA = $0A
tmpB = $0B
tmpC = $0C
tmpD = $0D
tmpE = $0E
tmpF = $0F

tmp10 = $10
tmp11 = $11
tmp12 = $12
tmp13 = $13
tmp14 = $14
tmp15 = $15
tmp16 = $16
tmp17 = $17
tmp18 = $18
tmp19 = $19
tmp1A = $1A
tmp1B = $1B
tmp1C = $1C
tmp1D = $1D
tmp1E = $1E
tmp1F = $1F

joy_raw  = $100 ;101 102 103
joy_prev = $104 ;105 106 107
joy_xor  = $108 ;109 10a 10b

addr0 = $26;27
addr1 = $28;29

random_seed = $2A;2B
mapper_tmp = $2C

tv_system_counter = $2D
tv_system_type = $2E	;0-NTSC 1-PAL 2-Dendy

nmi_toggle = $33
fade_counter = $34

cursor = $10C
cursor_target = $10D
cursor_smooth = $10E
animation_frame = $10F
frame_count = $110
chr_select = $111
test_delta = $112
frame_blink = $113

sprite_pos = $2F
sprite_ptr = $200

sprite_limit = $300

ram_opcode = $200
ram_opcode_fast_copy = $300
ram_table_x = $700

CFX_SIZE = $1E
CGX_START = $6000
CFX_CRC = $601E ;2 bytes
cfg_last_game = $6000
MENU_TYPE_GULL = 0
MENU_TYPE_SPACE = 1
MENU_TYPE_RETRO = 2
cfg_menu_type = $6001